/**
 * Memongo /v1 route table — the request-field truth every surface is
 * conformance-tested against (P2.2 route coverage; B2a full field sets).
 *
 * `requiredFields` + `optionalFields` together enumerate EVERY request field
 * a route accepts (body fields for POST routes, query fields for GET routes;
 * path parameters like {traceId} are implicit in the path). The conformance
 * tests assert the OpenAPI document declares each of them, so deleting any
 * optional field from the spec fails the build. `headerFields` covers header
 * parameters (e.g. Idempotency-Key).
 *
 * Keep aligned with apps/api/src/routes/v1.ts — the conformance test walks
 * the live router and fails when this table and the registered routes
 * disagree in either direction.
 */

export type ApiRouteMethod = "get" | "post"

export type ApiRouteContract = {
	/** OpenAPI-style path, e.g. "/v1/admin/traces/{traceId}". */
	path: string
	method: ApiRouteMethod
	operationId: string
	summary: string
	/**
	 * Request fields the route REQUIRES (spot-shape level): body fields for
	 * POST routes, query fields for GET routes. The conformance test asserts
	 * the OpenAPI document marks each of these as required.
	 */
	requiredFields: readonly string[]
	/**
	 * Every OTHER request field the route accepts (B2a). Together with
	 * requiredFields this is the route's full request field set; the
	 * conformance test asserts the OpenAPI document declares each one, so an
	 * undocumented field — or a documented field deleted from the spec — is
	 * caught. Path parameters are not listed (they live in `path`).
	 */
	optionalFields: readonly string[]
	/**
	 * Optional header parameters the route honors. The conformance test
	 * asserts each is documented as an OpenAPI header parameter.
	 */
	headerFields?: readonly string[]
	/**
	 * HTTP error statuses the route can deliberately return (excluding the
	 * middleware-level 401/403/413/429 shared by every route). The OpenAPI
	 * document must document each with the ApiError envelope.
	 */
	errorStatuses: readonly number[]
	/** MCP tool names that serve this route (canonical + aliases). */
	tools: readonly string[]
}

export const MEMONGO_API_ROUTES: readonly ApiRouteContract[] = [
	{
		path: "/v1/search",
		method: "post",
		operationId: "searchMemory",
		summary: "Search memory",
		requiredFields: ["query"],
		optionalFields: [
			"agentId",
			"limit",
			"minScore",
			"sessionKey",
			"scope",
			"scopeRef",
			"containerTag",
			"maxResults",
			"q",
		],
		errorStatuses: [400, 500],
		tools: ["memongo_search"],
	},
	{
		path: "/v1/search-kb",
		method: "post",
		operationId: "searchKnowledgeBase",
		summary: "Search the knowledge base",
		requiredFields: ["query"],
		optionalFields: [
			"agentId",
			"scopeRef",
			"limit",
			"minScore",
			"filter",
			"fusionMethod",
		],
		errorStatuses: [400, 500],
		tools: ["memongo_search_kb"],
	},
	{
		path: "/v1/search-detailed",
		method: "post",
		operationId: "searchMemoryDetailed",
		summary:
			"Advanced search with CRAG corrective retrieval, MMR diversity, constraint relaxation, and multi-source fusion",
		requiredFields: ["query"],
		optionalFields: [
			"agentId",
			"scope",
			"scopeRef",
			"limit",
			"maxResults",
			"minScore",
			"searchMode",
			"maxPasses",
			"returnPlan",
			"sourcePreference",
			"timeRange",
			"needExactEvidence",
			"conversationScope",
			"structuredScope",
			"referenceScope",
			"proceduralScope",
			"searchConfig",
		],
		errorStatuses: [400, 500],
		tools: ["memongo_search_detailed"],
	},
	{
		path: "/v1/recall-conversation",
		method: "post",
		operationId: "recallConversation",
		summary:
			"Recall prior conversation events by content, session, role, and exact time range",
		requiredFields: [],
		optionalFields: [
			"agentId",
			"query",
			"sessionId",
			"roles",
			"startTime",
			"endTime",
			"asOf",
			"timezone",
			"includeToolMessages",
			"limit",
		],
		errorStatuses: [400, 500],
		tools: ["memongo_recall_conversation", "memongo_recall_messages"],
	},
	{
		path: "/v1/import/conversations",
		method: "post",
		operationId: "importConversations",
		summary: "Import conversation history from a dataset file",
		requiredFields: ["datasetPath"],
		optionalFields: [
			"agentId",
			"scope",
			"limitConversations",
			"limitTurnsPerConversation",
		],
		errorStatuses: [400, 500],
		tools: [
			"memongo_import_conversations",
			"memongo_import_conversation_history",
		],
	},
	{
		path: "/v1/lifecycle/get",
		method: "post",
		operationId: "getLifecycleItem",
		summary: "Get a structured/procedure memory by stable handle",
		requiredFields: ["handle"],
		optionalFields: [],
		errorStatuses: [400, 404, 500],
		tools: ["memongo_lifecycle_get", "memongo_memory_get"],
	},
	{
		path: "/v1/lifecycle/update",
		method: "post",
		operationId: "updateLifecycleItem",
		summary: "Update a structured/procedure memory by stable handle",
		requiredFields: ["handle", "patch"],
		optionalFields: [],
		errorStatuses: [400, 404, 500],
		tools: ["memongo_lifecycle_update", "memongo_memory_update"],
	},
	{
		path: "/v1/lifecycle/delete",
		method: "post",
		operationId: "deleteLifecycleItem",
		summary: "Invalidate a structured/procedure memory by stable handle",
		requiredFields: ["handle"],
		optionalFields: ["invalidatedBy"],
		errorStatuses: [400, 404, 500],
		tools: ["memongo_lifecycle_delete", "memongo_memory_delete"],
	},
	{
		path: "/v1/lifecycle/history",
		method: "post",
		operationId: "getLifecycleHistory",
		summary: "Get lifecycle history for a stable handle",
		requiredFields: ["handle"],
		optionalFields: ["limit"],
		errorStatuses: [400, 404, 500],
		tools: ["memongo_lifecycle_history", "memongo_memory_history"],
	},
	{
		path: "/v1/procedures/outcome",
		method: "post",
		operationId: "reportProcedureOutcome",
		summary: "Report a procedure execution outcome",
		requiredFields: ["handle", "success"],
		optionalFields: ["note", "actorRole"],
		errorStatuses: [400, 404, 500],
		tools: ["memongo_procedure_outcome"],
	},
	{
		path: "/v1/memory/feedback",
		method: "post",
		operationId: "applyMemoryFeedback",
		summary: "Apply confirm/correct/irrelevant feedback to a memory",
		requiredFields: ["handle", "signal"],
		optionalFields: ["patch", "invalidatedBy", "note", "actorRole"],
		errorStatuses: [400, 404, 500],
		tools: ["memongo_memory_feedback"],
	},
	{
		path: "/v1/hydrate-active-slate",
		method: "post",
		operationId: "hydrateActiveSlate",
		summary: "Hydrate the active slate for a scope",
		requiredFields: [],
		optionalFields: ["agentId", "scope", "scopeRef", "maxItems"],
		errorStatuses: [400, 500],
		tools: ["memongo_hydrate_active_slate"],
	},
	{
		path: "/v1/discovery-projection",
		method: "post",
		operationId: "buildDiscoveryProjection",
		summary:
			"Build a discovery projection (entity/topic brief, changes, contradictions)",
		requiredFields: ["kind"],
		optionalFields: [
			"agentId",
			"query",
			"scope",
			"scopeRef",
			"maxItems",
			"timeRange",
		],
		errorStatuses: [400, 500],
		tools: ["memongo_discovery_projection"],
	},
	{
		path: "/v1/context-bundle",
		method: "post",
		operationId: "buildContextBundle",
		summary: "Build a token-budgeted context bundle",
		requiredFields: [],
		optionalFields: [
			"agentId",
			"query",
			"scope",
			"scopeRef",
			"sessionId",
			"tokenBudget",
			"maxActiveItems",
			"maxEvidenceItems",
			"maxRecentEvents",
			"includeDiscoveryProjection",
			"discoveryKind",
			"includeProfile",
			"timeRange",
			"mode",
		],
		errorStatuses: [400, 500],
		tools: ["memongo_build_context_bundle"],
	},
	{
		path: "/v1/state",
		method: "get",
		operationId: "getUnifiedState",
		summary: "Get the unified state family (profile, blocks, bundle)",
		requiredFields: [],
		optionalFields: ["agentId", "scope", "scopeRef"],
		errorStatuses: [500],
		tools: ["memongo_state_unified"],
	},
	{
		path: "/v1/read-file",
		method: "post",
		operationId: "readMemoryFile",
		summary: "Read a memory file by relative path",
		requiredFields: ["relPath"],
		optionalFields: ["agentId", "from", "lines"],
		errorStatuses: [400, 500],
		tools: ["memongo_read_file"],
	},
	{
		path: "/v1/add",
		method: "post",
		operationId: "addMemory",
		summary: "Append a user message (legacy alias of /v1/write-event)",
		requiredFields: ["content"],
		optionalFields: [
			"agentId",
			"sessionId",
			"containerTag",
			"scope",
			"scopeRef",
			"metadata",
			"customId",
			"expiresAt",
		],
		headerFields: ["Idempotency-Key"],
		errorStatuses: [400, 500],
		tools: ["memongo_add"],
	},
	{
		path: "/v1/write-event",
		method: "post",
		operationId: "writeConversationEvent",
		summary: "Write a conversation event",
		requiredFields: ["role", "body"],
		optionalFields: [
			"agentId",
			"sessionId",
			"scope",
			"scopeRef",
			"timestamp",
			"validAt",
			"invalidAt",
			"metadata",
			"customId",
			"expiresAt",
		],
		headerFields: ["Idempotency-Key"],
		errorStatuses: [400, 500],
		tools: ["memongo_write_event"],
	},
	{
		path: "/v1/write-events",
		method: "post",
		operationId: "writeConversationEventsBatch",
		summary:
			"Write a batch of conversation events with per-item idempotency receipts",
		requiredFields: ["events"],
		optionalFields: ["agentId", "sessionId", "scope", "scopeRef"],
		errorStatuses: [400, 500],
		tools: [],
	},
	{
		path: "/v1/extract",
		method: "post",
		operationId: "extractEvent",
		summary: "Schedule extraction for a conversation event",
		requiredFields: ["eventId"],
		optionalFields: ["agentId", "scope", "scopeRef"],
		errorStatuses: [400, 500],
		tools: ["memongo_extract"],
	},
	{
		path: "/v1/write-structured",
		method: "post",
		operationId: "writeStructuredMemory",
		summary: "Write a structured memory entry",
		requiredFields: ["entry"],
		optionalFields: ["agentId", "scope", "scopeRef"],
		errorStatuses: [400, 500],
		tools: ["memongo_write_structured"],
	},
	{
		path: "/v1/write-procedure",
		method: "post",
		operationId: "writeProcedure",
		summary: "Write a procedure memory entry",
		requiredFields: ["entry"],
		optionalFields: ["agentId", "scope", "scopeRef"],
		errorStatuses: [400, 500],
		tools: ["memongo_write_procedure"],
	},
	{
		path: "/v1/profile",
		method: "post",
		operationId: "getProfile",
		summary: "Synthesize the agent profile",
		requiredFields: [],
		optionalFields: [
			"agentId",
			"scope",
			"scopeRef",
			"containerTag",
			"maxEntities",
			"maxEpisodes",
			"maxPerType",
			"activityWindowMs",
		],
		errorStatuses: [400, 500],
		tools: ["memongo_profile"],
	},
	{
		path: "/v1/status",
		method: "get",
		operationId: "getStatus",
		summary: "Get memory provider status",
		requiredFields: [],
		optionalFields: [],
		errorStatuses: [500],
		tools: ["memongo_status"],
	},
	{
		path: "/v1/status/detailed",
		method: "get",
		operationId: "getDetailedStatus",
		summary: "Get detailed v2 status",
		requiredFields: [],
		optionalFields: [],
		errorStatuses: [500],
		tools: ["memongo_status_detailed"],
	},
	{
		path: "/v1/stats",
		method: "get",
		operationId: "getStats",
		summary: "Get memory statistics",
		requiredFields: [],
		optionalFields: [],
		errorStatuses: [500],
		tools: ["memongo_stats"],
	},
	{
		path: "/v1/sync",
		method: "post",
		operationId: "syncMemory",
		summary: "Sync memory sources",
		requiredFields: [],
		optionalFields: [],
		errorStatuses: [400, 500],
		tools: ["memongo_sync"],
	},
	{
		path: "/v1/probes/embedding",
		method: "get",
		operationId: "probeEmbedding",
		summary: "Probe embedding availability",
		requiredFields: [],
		optionalFields: [],
		errorStatuses: [500],
		tools: ["memongo_probe_embedding"],
	},
	{
		path: "/v1/probes/vector",
		method: "get",
		operationId: "probeVector",
		summary: "Probe vector search availability",
		requiredFields: [],
		optionalFields: [],
		errorStatuses: [500],
		tools: ["memongo_probe_vector"],
	},
	{
		path: "/v1/admin/relevance/explain",
		method: "post",
		operationId: "relevanceExplain",
		summary: "Explain relevance scoring for a query",
		requiredFields: ["query"],
		optionalFields: [
			"agentId",
			"sourceScope",
			"sessionKey",
			"maxResults",
			"minScore",
			"deep",
		],
		errorStatuses: [400, 500],
		tools: ["memongo_relevance_explain"],
	},
	{
		path: "/v1/admin/relevance/benchmark",
		method: "post",
		operationId: "relevanceBenchmark",
		summary: "Run the relevance benchmark harness",
		requiredFields: [],
		optionalFields: [
			"agentId",
			"datasetPath",
			"maxResults",
			"minScore",
			"retrievalLane",
			"datasetSha256",
			"embeddingConfig",
			"rerankerConfig",
			"qualityThresholds",
		],
		errorStatuses: [400, 500],
		tools: ["memongo_relevance_benchmark"],
	},
	{
		path: "/v1/admin/benchmarks/ingest",
		method: "post",
		operationId: "ingestBenchmark",
		summary: "Ingest a benchmark dataset",
		requiredFields: ["datasetPath"],
		optionalFields: [
			"agentId",
			"scope",
			"limitConversations",
			"limitTurnsPerConversation",
		],
		errorStatuses: [400, 500],
		tools: ["memongo_benchmark_ingest"],
	},
	{
		path: "/v1/admin/relevance/report",
		method: "get",
		operationId: "relevanceReport",
		summary: "Get the relevance telemetry report",
		requiredFields: [],
		optionalFields: [],
		errorStatuses: [500],
		tools: ["memongo_relevance_report"],
	},
	{
		path: "/v1/admin/relevance/sample-rate",
		method: "get",
		operationId: "relevanceSampleRate",
		summary: "Get the current relevance sample rate state",
		requiredFields: [],
		optionalFields: [],
		errorStatuses: [500],
		tools: ["memongo_relevance_sample_rate"],
	},
	{
		path: "/v1/admin/access-trends",
		method: "get",
		operationId: "getAccessTrends",
		summary: "Get memory access trends",
		requiredFields: [],
		optionalFields: [
			"agentId",
			"collection",
			"memoryIds",
			"windowDays",
			"limit",
		],
		errorStatuses: [400, 500],
		tools: ["memongo_admin_access_trends"],
	},
	{
		path: "/v1/admin/access-summaries",
		method: "get",
		operationId: "getAccessSummaries",
		summary: "Get memory access summaries",
		requiredFields: ["collection", "memoryIds"],
		optionalFields: ["agentId", "windowDays"],
		errorStatuses: [400, 500],
		tools: ["memongo_admin_access_summaries"],
	},
	{
		path: "/v1/admin/traces",
		method: "get",
		operationId: "listRecallTraces",
		summary: "List recall traces",
		requiredFields: [],
		optionalFields: ["agentId", "limit"],
		errorStatuses: [500],
		tools: ["memongo_admin_list_traces"],
	},
	{
		path: "/v1/admin/traces/{traceId}",
		method: "get",
		operationId: "getRecallTrace",
		summary: "Get a recall trace by id",
		requiredFields: [],
		optionalFields: ["agentId"],
		errorStatuses: [400, 404, 500],
		tools: ["memongo_admin_get_trace"],
	},
	{
		path: "/v1/jobs",
		method: "get",
		operationId: "listMemoryJobs",
		summary: "List memory jobs",
		requiredFields: [],
		optionalFields: ["agentId", "status", "jobType", "limit"],
		errorStatuses: [500],
		tools: ["memongo_list_jobs"],
	},
	{
		path: "/v1/jobs/{jobId}",
		method: "get",
		operationId: "getMemoryJob",
		summary: "Get a memory job by id",
		requiredFields: [],
		optionalFields: ["agentId"],
		errorStatuses: [400, 404, 500],
		tools: ["memongo_get_job"],
	},
	{
		path: "/v1/chain-trace",
		method: "post",
		operationId: "traceReasoningChain",
		summary: "Trace a reasoning chain from a fact",
		requiredFields: ["factId", "collection"],
		optionalFields: ["agentId", "maxDepth"],
		errorStatuses: [400, 500],
		tools: ["memongo_chain_trace"],
	},
	{
		path: "/v1/novelty-scan",
		method: "post",
		operationId: "scanNovelty",
		summary: "Scan for novel memories",
		requiredFields: [],
		optionalFields: ["agentId", "limit", "scope"],
		errorStatuses: [400, 500],
		tools: ["memongo_novelty_scan"],
	},
	{
		path: "/v1/consolidate",
		method: "post",
		operationId: "consolidateMemory",
		summary: "Run Dreamer consolidation — extract facts from events",
		requiredFields: [],
		optionalFields: [
			"agentId",
			"maxEvents",
			"minCombinedScore",
			"resolveContradictions",
			"llmDedup",
			"scope",
		],
		errorStatuses: [400, 500],
		tools: ["memongo_consolidate"],
	},
	{
		path: "/v1/self-edit",
		method: "post",
		operationId: "selfEditMemory",
		summary: "Directly edit a core memory block (user/persona/instructions)",
		requiredFields: ["block", "content"],
		optionalFields: ["action", "agentId"],
		errorStatuses: [400, 422, 500],
		tools: ["memongo_self_edit"],
	},
]
