/**
 * MCP tool field sets — the exact inputSchema property set every MCP tool
 * must expose (B2a). Paired with the /v1 route table: every tool named in a
 * route's `tools` list appears here, and the MCP conformance test
 * (apps/mcp/src/mcp-contract-conformance.test.ts) asserts the live tool
 * definitions match these property sets EXACTLY, so deleting any optional
 * field from an MCP tool schema — or inventing an undocumented one — fails
 * the build.
 */

export const MEMONGO_MCP_TOOL_FIELDS: Readonly<
	Record<string, readonly string[]>
> = {
	// Core tools (always registered)
	memongo_search: [
		"query",
		"agentId",
		"limit",
		"minScore",
		"scope",
		"scopeRef",
	],
	memongo_search_detailed: [
		"query",
		"agentId",
		"scope",
		"scopeRef",
		"limit",
		"maxResults",
		"minScore",
		"searchMode",
		"maxPasses",
		"returnPlan",
		"searchConfig",
	],
	memongo_add: [
		"content",
		"agentId",
		"sessionId",
		"metadata",
		"scope",
		"scopeRef",
		"customId",
		"expiresAt",
	],
	memongo_write_event: [
		"role",
		"body",
		"agentId",
		"sessionId",
		"timestamp",
		"validAt",
		"invalidAt",
		"scope",
		"scopeRef",
		"metadata",
		"customId",
		"expiresAt",
	],
	memongo_write_structured: ["entry", "agentId"],
	memongo_recall_conversation: [
		"query",
		"agentId",
		"scope",
		"scopeRef",
		"sessionId",
		"roles",
		"startTime",
		"endTime",
		"asOf",
		"timezone",
		"includeToolMessages",
		"limit",
	],
	memongo_build_context_bundle: [
		"query",
		"agentId",
		"scope",
		"scopeRef",
		"sessionId",
		"tokenBudget",
		"maxActiveItems",
		"maxEvidenceItems",
		"maxRecentEvents",
		"includeDiscoveryProjection",
		"discoveryKind",
		"includeProfile",
		"mode",
		"timeRange",
	],
	memongo_profile: ["agentId", "scope", "scopeRef"],
	memongo_state_unified: ["agentId", "scope", "scopeRef"],
	memongo_self_edit: ["block", "action", "content", "agentId"],
	memongo_memory_feedback: [
		"handle",
		"signal",
		"patch",
		"invalidatedBy",
		"note",
		"actorRole",
	],
	memongo_extract: ["eventId", "agentId", "scope", "scopeRef"],

	// Admin tools (MEMONGO_MCP_ADMIN=1)
	memongo_search_kb: [
		"query",
		"agentId",
		"limit",
		"scope",
		"scopeRef",
		"minScore",
		"filter",
		"fusionMethod",
	],
	memongo_read_file: ["relPath", "agentId", "from", "lines"],
	memongo_lifecycle_get: ["handle"],
	memongo_lifecycle_update: ["handle", "patch"],
	memongo_lifecycle_delete: ["handle", "invalidatedBy"],
	memongo_lifecycle_history: ["handle", "limit"],
	memongo_procedure_outcome: ["handle", "success", "note", "actorRole"],
	memongo_status: ["agentId"],
	memongo_chain_trace: ["factId", "collection", "agentId", "maxDepth"],
	memongo_novelty_scan: ["agentId", "limit", "scope", "scopeRef"],
	memongo_consolidate: [
		"agentId",
		"maxEvents",
		"minCombinedScore",
		"resolveContradictions",
		"llmDedup",
		"scope",
		"scopeRef",
	],
	memongo_import_conversations: [
		"datasetPath",
		"agentId",
		"scope",
		"scopeRef",
		"limitConversations",
		"limitTurnsPerConversation",
	],
	memongo_admin_access_trends: [
		"agentId",
		"collection",
		"memoryIds",
		"windowDays",
		"limit",
	],
	memongo_admin_access_summaries: [
		"agentId",
		"collection",
		"memoryIds",
		"windowDays",
	],
	memongo_admin_list_traces: ["agentId", "limit"],
	memongo_admin_get_trace: ["traceId", "agentId"],
	memongo_list_jobs: ["agentId", "status", "limit", "jobType"],
	memongo_get_job: ["jobId", "agentId"],
	memongo_hydrate_active_slate: ["agentId", "scope", "scopeRef", "maxItems"],
	memongo_discovery_projection: [
		"kind",
		"query",
		"agentId",
		"scope",
		"scopeRef",
		"maxItems",
	],
	memongo_write_procedure: ["entry", "agentId"],
	memongo_status_detailed: ["agentId"],
	memongo_stats: ["agentId"],
	memongo_sync: ["agentId", "reason", "force"],
	memongo_probe_embedding: ["agentId"],
	memongo_probe_vector: ["agentId"],
	memongo_relevance_explain: [
		"query",
		"agentId",
		"sourceScope",
		"maxResults",
		"minScore",
		"deep",
	],
	memongo_relevance_report: ["agentId", "windowMs"],
	memongo_relevance_sample_rate: ["agentId"],

	// Alias tools (MEMONGO_MCP_ALIASES=1); field sets mirror their canonicals.
	memongo_recall_messages: [
		"query",
		"agentId",
		"scope",
		"scopeRef",
		"sessionId",
		"roles",
		"startTime",
		"endTime",
		"asOf",
		"timezone",
		"includeToolMessages",
		"limit",
	],
	memongo_memory_get: ["handle"],
	memongo_memory_update: ["handle", "patch"],
	memongo_memory_delete: ["handle", "invalidatedBy"],
	memongo_memory_history: ["handle", "limit"],
	memongo_import_conversation_history: [
		"datasetPath",
		"agentId",
		"scope",
		"scopeRef",
		"limitConversations",
		"limitTurnsPerConversation",
	],
}
